/* eslint-disable */
/**
 * Generated API for Convex.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { anyApi } from "convex/server";

/**
 * A type describing your app's public Convex API.
 *
 * This `api` export is the primary way to interoperate with your Convex functions
 * in your frontend code.
 */
export const api = anyApi;