/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  DataModelFromSchema,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNamesInDataModel,
  Id,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema";

/**
 * The data model for this Convex app.
 */
export type DataModel = DataModelFromSchema<typeof schema>;

/**
 * A document in one of the tables in this Convex app.
 */
export type Document<T extends TableNamesInDataModel<DataModel>> = DocumentByName<
  DataModel,
  T
>;

/**
 * An ID for a document in one of the tables in this Convex app.
 */
export type Id<T extends TableNamesInDataModel<DataModel>> = GenericId<T>;

/**
 * A system table name in this Convex app.
 */
export type SystemTableNames = SystemTableNamesInDataModel<DataModel>;