/* eslint-disable */
/**
 * Generated utilities for implementing Convex functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
} from "convex/server";

/**
 * Define a query in this Convex app's public API.
 *
 * @param func - Your Python or JavaScript function.
 * @returns A wrapped function that can be called from the frontend.
 */
export const query = queryGeneric;

/**
 * Define a mutation in this Convex app's public API.
 *
 * @param func - Your Python or JavaScript function.
 * @returns A wrapped function that can be called from the frontend.
 */
export const mutation = mutationGeneric;

/**
 * Define an action in this Convex app's public API.
 *
 * @param func - Your Python or JavaScript function.
 * @returns A wrapped function that can be called from the frontend.
 */
export const action = actionGeneric;

/**
 * Define a query that is only accessible from within the Convex engine (e.g. by other functions).
 *
 * @param func - Your Python or JavaScript function.
 * @returns A wrapped function that can be called from other Convex functions.
 */
export const internalQuery = internalQueryGeneric;

/**
 * Define a mutation that is only accessible from within the Convex engine (e.g. by other functions).
 *
 * @param func - Your Python or JavaScript function.
 * @returns A wrapped function that can be called from other Convex functions.
 */
export const internalMutation = internalMutationGeneric;

/**
 * Define an action that is only accessible from within the Convex engine (e.g. by other functions).
 *
 * @param func - Your Python or JavaScript function.
 * @returns A wrapped function that can be called from other Convex functions.
 */
export const internalAction = internalActionGeneric;