"use client";

import React from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { Id } from "../../convex/_generated/dataModel";
import Navbar from "@/components/layout/Navbar";
import DeterministicOutput from "@/components/deterministic-output";
import { Loader2, ArrowLeft, Calendar, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";

const Report = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const analysis = useQuery(api.analyses.getAnalysisById, { id: id as Id<"analyses"> });

  if (analysis === undefined) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white dark:bg-[#0f0f0f]">
        <Loader2 className="h-8 w-8 animate-spin text-[#1877F2]" />
      </div>
    );
  }

  if (analysis === null) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-white dark:bg-[#0f0f0f] text-center p-4">
        <h1 className="text-4xl font-black mb-4">Report Not Found</h1>
        <p className="text-slate-500 mb-8">This analysis may have been deleted or the link is incorrect.</p>
        <Button onClick={() => navigate("/")} className="bg-[#1877F2]">Return Home</Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white dark:bg-[#0f0f0f] text-slate-900 dark:text-white">
      <Navbar />
      
      <main className="container mx-auto px-4 py-12">
        <div className="max-w-5xl mx-auto space-y-8">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-2">
              <Button 
                variant="ghost" 
                size="sm" 
                onClick={() => navigate("/")}
                className="mb-4 -ml-2 text-slate-500 hover:text-[#1877F2]"
              >
                <ArrowLeft className="h-4 w-4 mr-2" /> Back to Engine
              </Button>
              <h1 className="text-3xl md:text-5xl font-black tracking-tight">Shared Analysis Report</h1>
              <div className="flex flex-wrap items-center gap-4 text-xs font-bold text-slate-500 uppercase tracking-widest">
                <div className="flex items-center gap-1.5">
                  <Calendar className="h-3.5 w-3.5 text-[#1877F2]" />
                  {format(analysis.timestamp, "MMMM d, yyyy • HH:mm")}
                </div>
                <div className="flex items-center gap-1.5">
                  <ShieldCheck className="h-3.5 w-3.5 text-emerald-500" />
                  Verified {analysis.plan} Tier
                </div>
              </div>
            </div>
            
            <div className="p-4 rounded-2xl bg-blue-500/5 border border-blue-500/10 flex items-center gap-4">
              <div className="h-12 w-12 rounded-xl bg-[#1877F2] flex items-center justify-center shadow-lg shadow-blue-500/20">
                <Sparkles className="h-6 w-6 text-white" />
              </div>
              <div>
                <p className="text-[10px] font-bold text-slate-500 uppercase">Generated By</p>
                <p className="text-sm font-bold">SEO2026 Discovery Engine</p>
              </div>
            </div>
          </div>

          <div className="p-6 rounded-3xl bg-slate-50 dark:bg-white/[0.02] border border-slate-200 dark:border-white/10">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">Original Context</h3>
            <p className="text-lg font-medium leading-relaxed italic text-slate-700 dark:text-slate-300">
              "{analysis.input}"
            </p>
          </div>

          <div className="animate-in fade-in slide-in-from-bottom-8 duration-700">
            <DeterministicOutput data={analysis.result} />
          </div>

          <footer className="pt-12 border-t border-slate-100 dark:border-white/5 text-center">
            <p className="text-sm text-slate-500">
              This report was generated using deterministic AI search frameworks. 
              <br />
              <button onClick={() => navigate("/")} className="text-[#1877F2] font-bold hover:underline mt-2">
                Run your own analysis →
              </button>
            </p>
          </footer>
        </div>
      </main>
    </div>
  );
};

export default Report;